# Generated by Django 5.1.7 on 2025-04-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_analytics", "Can view analytics"),
                    ("manage_seo", "Can manage SEO"),
                    ("manage_marketing", "Can manage marketing"),
                    ("manage_support", "Can manage support"),
                    ("moderate_products", "Can moderate products"),
                    ("view_seller_dashboard", "Can view seller dashboard"),
                    ("manage_own_products", "Can manage own products"),
                    ("manage_own_categories", "Can manage own categories"),
                    ("manage_seo_fields", "Can manage SEO fields"),
                    ("import_export_products", "Can import/export products"),
                    ("browse_products", "Can browse products"),
                    ("purchase_products", "Can purchase products"),
                    ("leave_reviews", "Can leave reviews"),
                    ("track_orders", "Can track orders"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ["key"],
            },
        ),
    ]
